name: Cifrado

on: 
  push:
    branches:
      -main
    

jobs:
  job1: 
    name: 'Imprimir secret variable'
    runs-on: ubuntu-latest
    steps:
      - run: 
         echo ${{ secrets.SECRET_VARIABLE_ONE }}