name: Third

on:
  push:
    branches:
      - main

jobs:
 job1:
   name: 'primer job'
   runs-on: ubuntu-latest
   steps:
     - name: 'primer step'
       uses: actions/checkout@v3
       with: 
         repository: jmoyano/eati2023
         ref: main
         path: ./main 
     - name: 'segundo step' 
       uses: actions/checkout@v3
       with: 
         repository: jmoyano/eati2023
         ref: anotherbranch
         path: ./anotherbranch
     - run: |
          cat ./main/message.txt
          cat ./anotherbranch/message.txt